### ISSUE TITLE
Behind color is always white

### ISSUE THREAD

**Issue by ertandagdelen** [shirne/CartStepper#1]
Good widget, But behind color is always white, may be change to transparent.

**Comment by shirne** [comment]
![aaacolor](https://user-images.githubusercontent.com/2263157/129432613-0c2afe42-9f02-4506-922c-9a3f2495510c.png)
you mean this color?

**Comment by ertandagdelen** [comment]
![image](https://user-images.githubusercontent.com/5116451/129439008-c0f905b4-08fc-4d46-8351-219faed1499e.jpeg) nope, here, Your pics is good, i use in Cupertino style widgets. I wrap it with Material widget like;

`Material(child: CartStepper(axis: Axis.vertical,count: vHiz.toInt(),size: 50, didChangeCount: (int count) {setState(() { vHiz = count.toDouble(); });},),)`

I added
`color: Colors.transparent,` this to Material widget, it works for me, ty.
