### ISSUE TITLE
Do not show + sign only when 0

### ISSUE THREAD

**Issue by madhumitha-scholarly** [shirne/CartStepper#3]
Hello! This is an awesome widget. It would be even better if you can add an attribute that let's the user decide if they want to display only plus sign when the value is 0 or keep the the original counter with the number set to 0.

**Comment by shirne** [comment]
f0bf9e862bf5d538a65af32dc4fce3f981444b32

@madhumitha-scholarly 
Did this improvement solve your problem?

**Comment by madhumitha-scholarly** [comment]
Yes it did! Thank you for the enhancement!
