### ISSUE TITLE
editKeyboard attribute does not work for all android devices

### ISSUE THREAD

**Issue by madhumitha-scholarly** [shirne/CartStepper#4]
Just like TextFormField widget, if we want to limit the keyboard to only show numbers without decimal, 
for ios this attribute is sufficient:
editKeyboardType: TextInputType.numberWithOptions(decimal: false)

but for android, we need inputFormatters:  
inputFormatters: [
   //for android
   FilteringTextInputFormatter.digitsOnly
],

Would it be possible to add this attribute as well? Thank you!

**Comment by shirne** [comment]
v4.2.1  fix int type cast & add FilteringTextInputFormatter.digitsOnly for CartStepperInt
